### ISSUE TITLE
Vulkan SDK minimum version not specified

### ISSUE THREAD

**Issue by jherico** [Nadrin/quartz#1]
While trying to build, I failed on the shader compilation step because my version of glslangValidator didn't know what to do with `*.rchit.glsl`  shader files.  This was SDK version 1.1.82.  Updating to 1.1.101 fixed it, but you might wish to specify a version of the SDK in your readme that understands raytracing shaders.

**Comment by Nadrin** [comment]
Good catch! Added this to the README file.
